name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Update package manager and install pandoc
      run: sudo apt update && sudo apt install pandoc && sudo apt install pdflatex texlive
    - name: Checkout the project source code
      run: git checkout
    - name: List current workspace checkout
      run: ls -ail ${{ github.workspace }}/whitepaper/ && git status
    - name: Create the build directory
      run: mkdir ${{ github.workspace }}/build
    - name: Create pdf-format Whitepaper from the markdown source code
      run: pandoc ${{ github.workspace }}/whitepaper/gridcoin-whitepaper-draft.md -o ${{ github.workspace }}/build/gridcoin-whitepaper-draft.pdf
