name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      WHITEPAPER_FORMATS_DIR: whitepaper/formats
      WHITEPAPER_FILE_NAME_ROOT: gridcoin-whitepaper-draft
    steps:
    - uses: actions/checkout@v2
    - name: Update package manager and install o/s level dependencies
      run: sudo apt update && sudo apt install pandoc && sudo apt install node
    - name: Install secondary dependencies
      run: sudo npm install mdpdf -g
    - name: Checkout the project source code
      run: git checkout
    - name: List current workspace checkout
      run: ls -ail ${{ github.workspace }}/whitepaper/ && git status
    - name: Create the build directory
      run: mkdir -p ${{ github.workspace }}/build/${{ env.WHITEPAPER_FORMATS_DIR }}
    - name: Create the pdf-format whitepaper from the markdown source code
      run: |
        cd ${{ github.workspace }}/whitepaper && \
        mdpdf ${{ env.WHITEPAPER_FILE_NAME_ROOT }}.md && \
        mv ${{ env.WHITEPAPER_FILE_NAME_ROOT }}.pdf ${{ github.workspace }}/build/${{ env.WHITEPAPER_FORMATS_DIR }}/${{ env.WHITEPAPER_FILE_NAME_ROOT }}.pdf
